### ISSUE TITLE
[gui] Improve css support for the window size limiting

### ISSUE THREAD

**Issue by lc-soft** [lc-soft/LCUI#104]
I'm trying to use min-width and min-height to limit root window size, but it did not take effect directly until I adjust the window size.

``` css
root {
  min-width: 1280px;
  min-height: 800px;
}
```
