### ISSUE TITLE
[gui] max-width compute result are incorrect

### ISSUE THREAD

**Issue by lc-soft** [lc-soft/LCUI#113]
Expected result:

![image](https://user-images.githubusercontent.com/1730073/32948612-d1fe1968-cbda-11e7-89d8-dd4b34538c98.png)

Actual result:

![image](https://user-images.githubusercontent.com/1730073/32948554-9e3cfcde-cbda-11e7-92c7-826747589bb8.png)

![image](https://user-images.githubusercontent.com/1730073/32948710-2c3b3f1e-cbdb-11e7-891a-de738a907b7e.png)

![image](https://user-images.githubusercontent.com/1730073/32948740-440eb422-cbdb-11e7-82cf-65a529c2104f.png)

**Comment by lc-soft** [comment]
Here has a stylesheet select bug from [src/gui/css_library.c#L1104](https://github.com/lc-soft/LCUI/blob/a49140741a32c22d124cadbbf23221b9d2f0d2be/src/gui/css_library.c#L1104)

Example:

``` css
.col-6 {
  display: inline-block;
  max-width: 100%;
}
 .col {
  width: 100%;
  max-width: 100%;
}
.col-6 {
  max-width: 50%;
}
```

The effect of the above code is equivalent to the following code:

``` css
.col-6 {
  display: inline-block;
  max-width: 50%;
}
 .col {
  width: 100%;
  max-width: 100%;
}
```

The two stylesheets will be merged into a single styleesheet.
