### ISSUE TITLE
[layout] add simple support for flex display and justify-content 

### ISSUE THREAD

**Issue by lc-soft** [lc-soft/LCUI#117]
Now, we need to implement the layout below with the two buttons aligned to the right.

![image](https://user-images.githubusercontent.com/1730073/33939491-5e5f0122-e046-11e7-809a-ae60a5ed0ad6.png)

And we need to update the CSS parser to support the following css code:

``` css
.modal-footer {
    display: flex;
    justify-content: flex-end;
}
```

Reference documentation: https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content

Currently we only need to support `flex-start`, `flex-end`, `center` three values for the `justify-content`.
