### ISSUE TITLE
[layout] block element width overflow when parent setted margin spacing

### ISSUE THREAD

**Issue by lc-soft** [lc-soft/LCUI#121]
``` css
.parent {
  display: block;
  margin: 10px;
}
.child {
  display: block;
}
```

![qq 20180204175157](https://user-images.githubusercontent.com/1730073/35776293-ace6cf3e-09d4-11e8-883d-028770d993cb.png)
