### ISSUE TITLE
Improve window resizing on Windows

### ISSUE THREAD

**Issue by dossalab** [lc-soft/LCUI#164]
![20](https://user-images.githubusercontent.com/20026104/47671698-36d68680-dbc1-11e8-91d7-f07081f23d18.gif)

...Or at least make window border non-resizeable (for example, if root width & height properties set in css)

**Comment by lc-soft** [comment]
> make window border non-resizeable

You can try to set min size and max size, like this:

``` css
root {
  min-width: 900px;
  max-width: 900px;
  min-height: 600px;
  max-height: 600px;
}
```
