### ISSUE TITLE
[css] improve relative path support for url()

### ISSUE THREAD

**Issue by lc-soft** [lc-soft/LCUI#98]
For example:

``` css
/* app/assets/stylesheets/demo.css */
.test {
   background-image: url(../images/test.png);
}
```

Run `app/demo.exe`, it actually load target file is  `app/../images/test.png`, not `app/asssets/stylesheets/../images/test.png`, so  this function need improve.
